language: python
services:
    - redis

sudo: false

python:
    - 2.7
    - 3.5
env:
    - TEST_HIREDIS=0
    - TEST_HIREDIS=1
notifications:
    irc:
        - "irc.freenode.org#cycloneweb"
install:
    - if [[ $TEST_HIREDIS == '1' ]]; then pip install hiredis; fi
    - pip install .
script: trial tests/
